# Load location
checkpoint_save_path: model_checkpoints
step_to_load: 195

# DL param
multiprocess: true
num_workers: 1
load_dir: ./ds/MGN/cylinder_dataset
patch_size: [16, 16]
stride: [16, 16]
seq_len: 15
seq_interval: 2
resolution: 240
batch_size: 5
